name: 'Resolve Repo'
description: 'Resolve organization/repository full name.'

outputs:
  repository_full_name:
    value: ${{ steps.run.outputs.repository_full_name }}

runs:
  using: composite
  steps:
    - name: Resolver repositorio
      id: run
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        set -euo pipefail
        node "$GITHUB_ACTION_PATH/index.js"
