name: Example zero-config prepare

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Prepare Veracode Artifact
        id: veracode_build
        uses: JuanCunhaa/Afrika-Veracode-Build@v0.1.1
        with:
          config_mode: disabled
      - name: Show artifact
        run: echo "${{ steps.veracode_build.outputs.artifact_path }}"
